plugins:
  - removeTitle: true
  - removeXMLNS: true
  - removeDimensions: true
  - removeAttrs:
      attrs:
        - 'fill'
        - 'fill-rule'
        - 'stroke'
        - 'version'
        - 'class'
  - sortAttrs:
      order:
        - 'viewBox'
        - 'class'
  - collapseGroups: true
