plugins:
  - removeTitle: true
  - removeDimensions: true
  - removeViewBox: false
  - removeAttrs:
      attrs:
        - 'fill'
        - 'fill-rule'
        - 'stroke'
        - 'version'
        - 'class'
  - collapseGroups: true
  - addClassesToSVGElement:
      classNames: ['ridi_icon']
