# Site settings
title: RIDI Design System
baseurl: "/design-system"

# Build settings
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - Makefile
  - package.json
  - package-lock.json
  - README.md
